### ISSUE TITLE
V0.3 cannot upload file - Error 404 returned

### ISSUE THREAD

**Issue by lpdx** [adityak74/google-drive-upload-git-action#13]
My action script

```yml
name: On Push Run

on: push

jobs:
  install_conda:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "file.pdf"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true" # optional boolean
```
And I'm getting this message
`2022/12/07 20:34:53 Unable to retrieve files: googleapi: Error 404: File not found: ., notFound`.

Other info
- The file exists in the root folder;
- The GDRIVE_FOLDER_ID is acessible since I use it in another Python project;
- The service account is cofigured as owner.
