### ISSUE TITLE
Feature: add support for Windows runners

### ISSUE THREAD

**Issue by mvcaaa** [adityak74/google-drive-upload-git-action#15]
Simplest workflow:

```yaml
name: make something useful

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Installer executable
        run: |
          cd 'Installer'
          makensis installer.nsi
      - uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
          filename: 'installer.exe'
          folderId: ${{ secrets.FILE_GDRIVE_FOLDER_ID }}
          overwrite: "true"
          mirrorDirectoryStructure: "true"
```

Failing with:
```log
Run adityak7[4](https://github.com/mvcaaa/installer/actions/runs/nnnnnnnnnnnn/jobs/mmmmmmmm#step:13:4)/google-drive-upload-git-action@main
  with:
    credentials: ***
    filename: Installer.exe
    folderId: ***
    overwrite: true
    mirrorDirectoryStructure: true
Error: Container action is only supported on Linux
```
