### ISSUE TITLE
Error: base64 decoding of 'credentials' failed with error: illegal base64 data at input byte 3168

### ISSUE THREAD

**Issue by ran-helfer** [adityak74/google-drive-upload-git-action#23]
HI, 

I am using this action and everything seem to work when i use `folderId` and `credentials` as strings with `""` :

```
     - name: Upload to G-Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: "someverylongbase64string"
          filename: "${{ needs.zip_and_cache.outputs.CURRENT_VERSION }}/${{ needs.zip_and_cache.outputs.BUILD_NUMBER }}/VizAINotify-${{ needs.zip_and_cache.outputs.VERSION_WITH_BUILD_NUMBER }}.zip"
          folderId: "myFolderId"
          overwrite: "true"
          mirrorDirectoryStructure: "true"

```

So happy with the results i added two github action secrets as:

```
GOOGLE_UPLOAD_API_KEY =  someverylongbase64string
GOOGLE_UPLOAD_IOS_DRIVE =  myFolderId
```

and now when running:

  ```
   - name: Upload to G-Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_UPLOAD_API_KEY }}
          filename: "${{ needs.zip_and_cache.outputs.CURRENT_VERSION }}/${{ needs.zip_and_cache.outputs.BUILD_NUMBER }}/VizAINotify-${{ needs.zip_and_cache.outputs.VERSION_WITH_BUILD_NUMBER }}.zip"
          folderId: ${{ secrets.GOOGLE_UPLOAD_IOS_DRIVE }}
          overwrite: "true"
          mirrorDirectoryStructure: "true"
```

I get:

`Error: base64 decoding of 'credentials' failed with error: illegal base64 data at input byte 3168`

Is anyone familiar with such error ? 

What should i do ? 

Should i update my keys with `""` ?

```
GOOGLE_UPLOAD_API_KEY =  "someverylongbase64string"
GOOGLE_UPLOAD_IOS_DRIVE =  "myFolderId"
```

Will appreciate any help 🙏🏻
