### ISSUE TITLE
v0.2 can not upload to gdrive

### ISSUE THREAD

**Issue by douglarek** [adityak74/google-drive-upload-git-action#7]
```
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "guwenguanzhi.epub"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          name: "古文觀止.epub"
          overwrite: "true"

```

```
2022/07/12 06:44:30 Unable to retrieve files: googleapi: Error 404: File not found: ., notFound
```
